import { useState, useEffect, useMemo } from 'react';
import {
  Card,
  Row,
  Col,
  List,
  Input,
  // Button now comes from src/ui — see the import below.
  Alert,
  message,
  Modal,
  Spin,
  Typography,
  Space,
  Form,
  Select,
  Switch,
  Tooltip,
} from 'antd';
import {
  MailOutlined,
  SaveOutlined,
  SearchOutlined,
  CopyOutlined,
  PlusOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import EmptyState from '../components/common/EmptyState';
// DISABLED 2026-08-29 (Stage 5.4) — replaced by src/ui's PageHeader below, which this
// page was the last consumer of. To restore: uncomment and swap the two tags back.
// import PageHeader from '../components/common/PageHeader';
import { DesignScope, PageShell, PageHeader, Surface, Button } from '../ui';
// After '../ui' so page rules win on equal specificity.
import '../styles/pages/email-management.css';
import emailTemplateService from '../services/emailTemplateService';
import useTheme from '../hooks/useTheme';
import useAuth from '../hooks/useAuth';
import EmailBodyEditor, { EmailEditorTabs, FULL_TOOLBAR, sanitizeDoc } from '../components/common/EmailBodyEditor';
import { isFullHtmlDocument, brandedPreviewParts } from '../utils/emailPreview';

dayjs.extend(relativeTime);

const { Title, Text } = Typography;

// Structural placeholders the sending service injects as HTML fragments (not
// recruiter content) — excluded from required-placeholder validation so they
// can be freely removed from a body. Mirrors OPTIONAL_PLACEHOLDERS in
// backend/src/controllers/emailTemplate.controller.js.
const OPTIONAL_PLACEHOLDERS = new Set(['teams_line', 'reason_line']);

// Tokens that render a whole HTML block the sending service builds, rather than
// a value a recruiter types. Without this note the screen just shows a bare
// {{teams_line}} and looks like something is missing — the Teams block in
// particular is generated by buildTeamsBlock() in interviewSchedule.service.js
// because it interpolates the live join URL, Meeting ID and passcode.
const STRUCTURAL_PLACEHOLDER_NOTES = {
  teams_line: 'Renders the Microsoft Teams join block (button, link, Meeting ID, passcode). Generated automatically at send time — its wording is managed in code, not here.',
  reason_line: 'Renders the cancellation reason, when one was given.',
  notes_line: "Renders the recruiter's interview notes, when present.",
};

// Creating templates from the UI isn't needed right now — flip this back to
// true to bring the "New Template" button back without re-plumbing anything.
const SHOW_NEW_TEMPLATE_BUTTON = false;

// Dummy replacements for the Live Preview tab — a template's real values
// (candidate name, interview time, etc.) don't exist until send time, so
// preview substitutes sample text for every token it recognizes.
const dummyReplacements = {
  candidate_name: 'John Doe',
  job_title: 'Senior Node.js Engineer',
  position: 'Senior Node.js Engineer',
  interview_start: '15 June 2026, 02:00 PM IST',
  interview_end: '15 June 2026, 03:00 PM IST',
  interview_link: 'https://interview.zeko.ai/interview/senior-node-dev',
  cancel_reason: 'Hiring manager rescheduled due to client conflict',
  interview_stage: 'HR SCREENING',
  vendor_name: 'Alpha Partners Agency',
  candidate_email: 'johndoe@example.com',
  candidate_phone: '+91 98765 43210',
  upload_link: 'https://ats.aapnainfotech.com/missing-jd-upload?token=xyz',
  recruiter_name: 'Sarah Jenkins',
  ctc: '18 LPA',
  joining_date: '01 July 2026',
  // Technical-round interview templates (#22–27).
  stage_label: 'Technical Round 1',
  interview_when: '28 July 2026 at 11:00 AM IST',
  previous_when: '25 July 2026 at 03:00 PM IST',
  duration: '60',
  teams_line: '<p style="margin:16px 0;"><a href="https://teams.microsoft.com/l/meetup-join/sample" style="background:#7a922e;color:#fff;padding:11px 22px;text-decoration:none;border-radius:8px;font-weight:700;display:inline-block;">Join the Microsoft Teams meeting</a></p>',
  reason_line: '<p><strong>Reason:</strong> Interviewer unavailable</p>',
  role_paragraph: '<p>Based on your profile, you are a strong match for this role — we were particularly impressed by your relevant experience and technical background.</p>',
  uploaded_by: 'Priya Sharma (HR)',
  interviewer_name: 'Rajesh Kumar',
  scorecard_link: 'https://ats.aapnainfotech.com/scorecard/sample-token',
  confirm_link: 'https://ats.aapnainfotech.com/pipeline/confirm/sample-token',
  absent_party: 'the candidate did not join',
  notes_line: '<p><strong>Notes:</strong> Please bring a valid photo ID.</p>',
};

/** Substitutes every recognized {token}/{{token}} with its dummy sample value. */
function compileDummyPreview(subject, body) {
  let compiledSubject = subject;
  let compiledBody = body;
  for (const [key, val] of Object.entries(dummyReplacements)) {
    compiledSubject = compiledSubject.split(`{{${key}}}`).join(val).split(`{${key}}`).join(val);
    compiledBody = compiledBody.split(`{{${key}}}`).join(val).split(`{${key}}`).join(val);
  }
  return { subject: compiledSubject, body: compiledBody };
}

/**
 * A representative "To:" address for the Live Preview mock email chrome —
 * the real recipient varies by template (candidate, panel, internal HR,
 * vendor), but EmailPreviewPane always defaulted to candidate@example.com
 * regardless, which is actively misleading for anything not candidate-facing.
 */
function sampleRecipientFor(template) {
  if (!template) return 'candidate@example.com';
  if (template.category === 'vendor_status') return 'vendor@partneragency.com';
  if (/panel|interviewer|leadership round/i.test(template.name)) return 'interviewer@aapnainfotech.com';
  if (/internal hr/i.test(template.name)) return 'hr-team@aapnainfotech.com';
  return 'candidate@example.com';
}

export default function EmailManagement() {
  const { isDark } = useTheme();
  // Creating a template is admin-only server-side (requireAdmin). Mirrors the
  // gate on Settings.jsx so the button is not offered to someone who would only
  // get a 403 back. Editing an existing template stays open to recruiters.
  const { user } = useAuth();
  const isAdmin = user?.role && ['admin', 'superadmin'].includes(user.role.toLowerCase());

  const [templates, setTemplates] = useState([]);
  const [filteredTemplates, setFilteredTemplates] = useState([]);
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');

  // Form states
  const [subject, setSubject] = useState('');
  const [bodyHtml, setBodyHtml] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [validationError, setValidationError] = useState('');
  const [isDirty, setIsDirty] = useState(false);

  // Create-template modal
  const [createOpen, setCreateOpen] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [createBody, setCreateBody] = useState('');
  const [createForm] = Form.useForm();

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    setIsLoading(true);
    try {
      const res = await emailTemplateService.getEmailTemplates();
      if (res.data.status === 'success') {
        setTemplates(res.data.data);
        setFilteredTemplates(res.data.data);
      } else {
        message.error('Failed to load templates.');
      }
    } catch (err) {
      console.error(err);
      message.error('Error fetching email templates.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    let result = templates;
    if (selectedCategory !== 'all') {
      result = result.filter(t => t.category === selectedCategory);
    }
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      result = result.filter(
        t =>
          t.name.toLowerCase().includes(query) ||
          t.subject.toLowerCase().includes(query)
      );
    }
    setFilteredTemplates(result);
  }, [searchQuery, selectedCategory, templates]);

  const applySelection = (template) => {
    setSelectedTemplate(template);
    setSubject(template.subject);
    setBodyHtml(template.body_html);
    setValidationError('');
    setIsDirty(false);
  };

  const handleSelectTemplate = (template) => {
    // Guard against silently discarding unsaved edits when switching templates.
    if (selectedTemplate && template.id !== selectedTemplate.id && isDirty) {
      Modal.confirm({
        title: 'Discard unsaved changes?',
        content: `You have unsaved edits to "${selectedTemplate.name}". Switching templates will discard them.`,
        okText: 'Discard changes',
        okButtonProps: { danger: true },
        cancelText: 'Keep editing',
        centered: true,
        onOk: () => applySelection(template),
      });
      return;
    }
    applySelection(template);
  };

  // Resolves each placeholder to its final, insert-ready bracketed form once
  // per template selection (e.g. `{token}` vs `{{token}}`, matching whichever
  // style this template's own placeholders array already uses).
  const resolvedPlaceholders = useMemo(() => {
    if (!selectedTemplate) return [];
    const hasSingleBrackets = selectedTemplate.placeholders.some(
      p => p.startsWith('{') && !p.startsWith('{{')
    );
    return selectedTemplate.placeholders.map((p) => {
      const clean = p.replace(/[{}]/g, '');
      return hasSingleBrackets ? `{${clean}}` : `{{${clean}}}`;
    });
  }, [selectedTemplate]);

  // Pre-save placeholder validation
  const validateTemplate = (sub, body) => {
    if (!selectedTemplate) return true;
    const contentToValidate = (sub + ' ' + body).toLowerCase();
    const missing = [];

    for (const p of selectedTemplate.placeholders) {
      const cleanP = p.replace(/[{}]/g, '').toLowerCase();
      // Inject-only structural fragments are optional (see OPTIONAL_PLACEHOLDERS).
      if (OPTIONAL_PLACEHOLDERS.has(cleanP)) continue;
      const hasDouble = contentToValidate.includes(`{{${cleanP}}}`);
      const hasSingle = contentToValidate.includes(`{${cleanP}}`);
      let hasAlias = false;
      if (cleanP === 'job_title' || cleanP === 'position') {
        hasAlias =
          contentToValidate.includes('{{job_title}}') ||
          contentToValidate.includes('{job_title}') ||
          contentToValidate.includes('{{position}}') ||
          contentToValidate.includes('{position}');
      }
      if (!hasDouble && !hasSingle && !hasAlias) missing.push(p);
    }

    if (missing.length > 0) {
      setValidationError(
        `Validation Failed: The following required placeholders are missing from your subject or body: ${missing.join(', ')}`
      );
      return false;
    }
    setValidationError('');
    return true;
  };

  const handleSave = async () => {
    const cleanBody = sanitizeDoc(bodyHtml);

    if (!validateTemplate(subject, cleanBody)) {
      message.error('Cannot save: Missing mandatory placeholders.');
      return;
    }

    setIsSaving(true);
    try {
      const res = await emailTemplateService.updateEmailTemplate(selectedTemplate.id, {
        subject,
        body_html: cleanBody,
      });

      if (res.data.status === 'success') {
        message.success('Template saved successfully!');
        setBodyHtml(cleanBody);
        setTemplates(prev =>
          prev.map(t =>
            t.id === selectedTemplate.id
              ? { ...t, subject, body_html: cleanBody, modified_at: new Date() }
              : t
          )
        );
        // Keep the same id so the editor does not reload.
        setSelectedTemplate(prev => ({
          ...prev,
          subject,
          body_html: cleanBody,
          modified_at: new Date(),
        }));
        setIsDirty(false);
      } else {
        message.error(res.data.message || 'Failed to save template.');
      }
    } catch (err) {
      console.error(err);
      message.error(
        err.response?.data?.message || err?.message || 'Error occurred while saving the email template.'
      );
    } finally {
      setIsSaving(false);
    }
  };

  const handleBodyChange = (html) => {
    setBodyHtml(html);
    setValidationError('');
    setIsDirty(true);
  };

  const openCreate = () => {
    createForm.resetFields();
    setCreateBody('');
    setCreateOpen(true);
  };

  const handleCreate = async () => {
    let values;
    try {
      values = await createForm.validateFields();
    } catch {
      return; // antd has already marked the offending fields
    }

    const cleanBody = sanitizeDoc(createBody);
    if (!cleanBody.trim()) {
      createForm.setFields([{ name: 'body_html', errors: ['A template needs a body.'] }]);
      return;
    }

    setIsCreating(true);
    try {
      const res = await emailTemplateService.createEmailTemplate({
        name: values.name,
        category: values.category || 'general',
        subject: values.subject,
        body_html: cleanBody,
        placeholders: values.placeholders || [],
        is_active: values.is_active !== false,
      });

      if (res.data.status === 'success') {
        const created = res.data.data;
        message.success(`Template "${created.name}" created.`);
        setTemplates(prev => [...prev, created]);
        setCreateOpen(false);
        // Land the user in the new template's editor — creating one is almost
        // always the first half of writing it.
        applySelection(created);
      } else {
        message.error('Failed to create the template.');
      }
    } catch (err) {
      // 409 means the name is taken. That message is the useful one and belongs
      // on the field, not in a toast that disappears.
      const serverMessage = err.response?.data?.message;
      if (err.response?.status === 409 && serverMessage) {
        createForm.setFields([{ name: 'name', errors: [serverMessage] }]);
      } else {
        message.error(serverMessage || err?.message || 'Error creating the email template.');
      }
    } finally {
      setIsCreating(false);
    }
  };

  const dummyPreview = useMemo(() => compileDummyPreview(subject, bodyHtml), [subject, bodyHtml]);

  // The branded chrome the editor renders AROUND the editable body, so a
  // recruiter edits the template inside the real AAPNA email rather than in a
  // bare text box. Only for fragment-bodied templates: a legacy full-HTML
  // template already IS the whole document, and wrapping it would double the
  // shell. Passing this also switches useEmailIframeEditor into
  // protected-chrome mode, where the header/footer are read-only and only the
  // body slot is saved back — which is what stops a save from rewriting a
  // fragment into a full <html> document and silently disabling its branding.
  // Explanations for any structural token this template declares, so the
  // recruiter knows what {{teams_line}} & co. actually produce.
  const structuralNotes = useMemo(() => {
    const declared = (selectedTemplate?.placeholders || []).map((p) => String(p).replace(/[{}]/g, '').trim());
    return Object.entries(STRUCTURAL_PLACEHOLDER_NOTES)
      .filter(([token]) => declared.includes(token))
      .map(([token, note]) => ({ token, note }));
  }, [selectedTemplate]);

  const editorWrapper = useMemo(
    () => (selectedTemplate && !isFullHtmlDocument(selectedTemplate.body_html)
      ? brandedPreviewParts({ title: subject, bodyHtml })
      : undefined),
    [selectedTemplate, subject, bodyHtml],
  );

  // A SEPARATE wrapper for the Live Preview tab, built from dummyPreview's
  // sample-substituted subject rather than the raw one editorWrapper uses.
  // Without this, EmailPreviewPane's mail-client "Subject:" line (which reads
  // `previewSubject` directly) showed sample text ("... Technical Round 1:
  // John Doe") while the actual green header band inside the branded shell —
  // baked from `wrapper.headerHtml`, which ignores the subject prop entirely
  // once a wrapper is present — still showed the raw, un-substituted
  // "{{stage_label}}: {{candidate_name}}". Reusing editorWrapper for both
  // surfaces is deliberately NOT an option: the Editor tab must keep showing
  // the real, editable subject in its header (that IS the template), only
  // Live Preview should show the compiled sample.
  const previewWrapper = useMemo(
    () => (selectedTemplate && !isFullHtmlDocument(selectedTemplate.body_html)
      ? brandedPreviewParts({ title: dummyPreview.subject, bodyHtml: dummyPreview.body })
      : undefined),
    [selectedTemplate, dummyPreview],
  );

  const handleCopyHtml = async () => {
    try {
      await navigator.clipboard.writeText(bodyHtml || '');
      message.success('Email HTML copied to clipboard.');
    } catch {
      message.error('Could not copy to clipboard.');
    }
  };

  const categories = [
    { key: 'all', label: 'All Templates' },
    { key: 'general', label: 'General / Alerts' },
    { key: 'shortlist', label: 'Shortlist' },
    { key: 'interview', label: 'Interviews' },
    { key: 'stage_outcome', label: 'Stage Outcome' },
    { key: 'offer', label: 'Offer Letter' },
    { key: 'rejection', label: 'Rejection' },
    { key: 'onboarding', label: 'Onboarding' },
    { key: 'vendor_status', label: 'Vendor Updates' },
  ];

  // The list-item tag and the editor header tag both used to show the raw DB
  // slug (STAGE_OUTCOME / stage_outcome, disagreeing with each other on
  // casing) instead of reusing the friendly label the filter chips already
  // define above.
  const categoryLabel = (key) => categories.find((c) => c.key === key)?.label || key;

  // Keyboard activation helper for custom clickable elements.
  const onActivate = (handler) => (e) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handler();
    }
  };

  return (
    <DesignScope>
      <PageShell width="wide" className="stagger-children email-page">
      {/* The app's standard page header — every other screen opens with one, and
          this was PageHeader's last consumer before a redesign dropped it. The
          gap below is tightened to --space-4 for this page only (see
          `.email-page .page-header`), since the editing surface is sized to a
          whole email and every band above it comes out of that budget. */}
      <PageHeader
        eyebrow="Communications"
        title="Email Templates"
        subtitle="Edit the subject, body and placeholders of every automated email the system sends."
      />

      {/* One slim control row under it. Search and category live here rather
          than inside the list pane, which is what lets both panes share a
          single top edge. */}
      <div className="email-toolbar">
        <Input
          prefix={<SearchOutlined className="em-prefix-icon" />}
          placeholder="Search templates"
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          allowClear
          className="email-toolbar__search"
        />

        {/* Was nine CheckableTags wrapping onto three rows. */}
        <Select
          value={selectedCategory}
          onChange={setSelectedCategory}
          options={categories.map(c => ({ value: c.key, label: c.label }))}
          popupMatchSelectWidth={false}
          className="email-toolbar__category"
        />

        <Text type="secondary" className="em-count">
          {filteredTemplates.length} {filteredTemplates.length === 1 ? 'template' : 'templates'}
        </Text>

        <div className="em-spacer" />

        {selectedTemplate && (
          <Text
            type="secondary"
            className={`em-count${isDirty ? ' em-count--dirty' : ''}`}
          >
            {isDirty
              ? 'Unsaved changes'
              : selectedTemplate.modified_at
                ? `Saved ${dayjs(selectedTemplate.modified_at).fromNow()}`
                : ''}
          </Text>
        )}

        {SHOW_NEW_TEMPLATE_BUTTON && isAdmin && (
          <Button emphasis="soft" icon={<PlusOutlined />} onClick={openCreate}>
            New Template
          </Button>
        )}

        <Button
          emphasis="solid"
          icon={<SaveOutlined />}
          onClick={handleSave}
          loading={isSaving}
          disabled={!selectedTemplate || !isDirty}
          className="email-toolbar__save"
        >
          Save changes
        </Button>
      </div>

      <Row gutter={24} align="stretch" className="email-page-row">
        {/* Left Side: Templates List */}
        <Col xs={24} md={8}>
          {/* Tier 3 — a records list. Was `.glass-3 no-lift`, which signalled the
              same intent through a class the Surface primitive now owns outright. */}
          <Surface tier={3} padding="none" className="email-list-card em-pane">
            <div className="em-list-body">
            {/* List — search and category now live in the page toolbar. */}
            {isLoading ? (
              <div className="em-loading">
                <Spin size="large" />
                <Text className="em-loading__label">
                  Loading templates...
                </Text>
              </div>
            ) : filteredTemplates.length === 0 ? (
              // Was a bare "No templates found." — which does not say whether the
              // search excluded everything or there is genuinely nothing here.
              // Two shapes, and the recoverable one offers the way back.
              searchQuery || selectedCategory !== 'all' ? (
                <EmptyState
                  size="sm"
                  icon={<SearchOutlined />}
                  title="No templates match"
                  body="Nothing matches the current search and category. Clear them to see every template."
                  actionLabel="Clear filters"
                  onAction={() => { setSearchQuery(''); setSelectedCategory('all'); }}
                />
              ) : (
                <EmptyState
                  size="sm"
                  icon={<MailOutlined />}
                  title="No email templates yet"
                  body="Templates control the wording of every automated email the system sends."
                  actionLabel={SHOW_NEW_TEMPLATE_BUTTON && isAdmin ? 'New template' : undefined}
                  onAction={SHOW_NEW_TEMPLATE_BUTTON && isAdmin ? openCreate : undefined}
                />
              )
            ) : (
              <List
                dataSource={filteredTemplates}
                className="email-template-list"
                renderItem={item => {
                  const isSelected = selectedTemplate?.id === item.id;
                  return (
                    // Denser than before: the category tag and the "Active" pill
                    // repeated on every row were noise — category is now the
                    // toolbar filter, and status is a single dot. Only the two
                    // genuinely exceptional states still carry words.
                    <List.Item
                      onClick={() => handleSelectTemplate(item)}
                      onKeyDown={onActivate(() => handleSelectTemplate(item))}
                      role="button"
                      tabIndex={0}
                      aria-pressed={isSelected}
                      className={`template-list-item${isSelected ? ' is-selected' : ''}`}
                    >
                      <div style={{ display: 'flex', gap: 10, width: '100%', minWidth: 0 }}>
                        <Tooltip title={item.is_active ? 'Active' : 'Inactive'}>
                          <span
                            className={`template-list-item__dot${item.is_active ? '' : ' template-list-item__dot--off'}`}
                          />
                        </Tooltip>
                        <div className="em-item-body">
                          <div className="template-list-item__name">{item.name}</div>
                          <div className="template-list-item__sub">
                            {item.neverSends ? (
                              <Tooltip title="This template is mapped to a stage outcome that is deliberately never sent — edits here have no effect.">
                                <span className="em-never">Never sends</span>
                              </Tooltip>
                            ) : (
                              item.subject
                            )}
                          </div>
                        </div>
                      </div>
                    </List.Item>
                  );
                }}
              />
            )}
            </div>
          </Surface>
        </Col>

        {/* Right Side: Editor Panel */}
        <Col xs={24} md={16}>
          {/* No `overflow: hidden` on the editor body: the editor/preview frames
              are sized to their own content, so clipping would cut the bottom off a
              tall email — the exact symptom this page had. Save moved to the page
              toolbar, so the head is just identity, which keeps it to one line. */}
          {selectedTemplate ? (
            <Surface tier={3} padding="none" className="email-editor-card em-pane">
              <div className="em-pane__head">
                <div className="em-item-meta">
                  <div className="email-editor-card__name">{selectedTemplate.name}</div>
                  <Text type="secondary" className="em-caption">
                    {categoryLabel(selectedTemplate.category)}
                  </Text>
                </div>
              </div>
              <div className="em-editor-body">
              {selectedTemplate.neverSends && (
                <Alert
                  type="warning"
                  showIcon
                  message="This template is mapped to a stage outcome that is deliberately never sent — edits here have no effect on any email."
                  className="em-alert em-alert--sm"
                />
              )}

              {validationError && (
                <Alert
                  message={validationError}
                  type="error"
                  showIcon
                  closable
                  onClose={() => setValidationError('')}
                  className="em-alert"
                />
              )}

              {/* Label inline rather than stacked above — one line instead of two. */}
              <div className="email-subject-row">
                <span className="email-subject-row__label">Subject</span>
                <Input
                  value={subject}
                  onChange={e => {
                    setSubject(e.target.value);
                    setValidationError('');
                    setIsDirty(true);
                  }}
                  placeholder="Enter email subject line..."
                  maxLength={255}
                  showCount
                  variant="borderless"
                  className="email-subject-row__input"
                />
              </div>

              <EmailEditorTabs
                key={selectedTemplate.id}
                bodyHtml={bodyHtml}
                onBodyChange={handleBodyChange}
                subject={subject}
                previewSubject={dummyPreview.subject}
                previewBodyHtml={dummyPreview.body}
                placeholders={resolvedPlaceholders}
                toolbar={FULL_TOOLBAR}
                isDark={isDark}
                to={sampleRecipientFor(selectedTemplate)}
                wrapper={editorWrapper}
                previewWrapper={previewWrapper}
                autoHeight
                fillHeight
                htmlExtra={
                  <Button size="sm" emphasis="soft" icon={<CopyOutlined />} onClick={handleCopyHtml}>
                    Copy HTML
                  </Button>
                }
              />

              {structuralNotes.length > 0 && (
                <div className="em-notes">
                  {structuralNotes.map(({ token, note }) => (
                    <div key={token}>
                      <Text code className="em-token">{`{{${token}}}`}</Text>{' '}
                      <Text type="secondary" className="em-caption">{note}</Text>
                    </div>
                  ))}
                </div>
              )}
              </div>
            </Surface>
          ) : (
            <Surface tier={3} padding="relaxed" className="email-placeholder-card em-placeholder">
              <Space direction="vertical" size={14}>
                <MailOutlined className="em-placeholder__icon" />
                <Title level={4} className="em-placeholder__title">
                  No Template Selected
                </Title>
                <Text type="secondary" className="em-placeholder__copy">
                  Select an email template from the list on the left to edit its subject,
                  body, and placeholders — then preview it exactly as recipients will see it.
                </Text>
              </Space>
            </Surface>
          )}
        </Col>
      </Row>

      {/* CREATE TEMPLATE — admin only. Closes the gap that sent every new
          template through a developer and a seed script run. */}
      <Modal
        title={<span className="em-modal-title">New Email Template</span>}
        open={createOpen}
        onOk={handleCreate}
        onCancel={() => setCreateOpen(false)}
        okText="Create Template"
        okButtonProps={{ loading: isCreating }}
        width={820}
        destroyOnClose
        styles={{ body: { maxHeight: '70vh', overflowY: 'auto', paddingRight: 12 } }}
      >
        <Form
          form={createForm}
          layout="vertical"
          style={{ marginTop: 12 }}
          initialValues={{ category: 'general', is_active: true }}
        >
          <Row gutter={16}>
            <Col xs={24} md={14}>
              <Form.Item
                name="name"
                label="Template name"
                extra="Used to look this template up at send time, so it must be unique."
                rules={[{ required: true, message: 'A template needs a name.' }]}
              >
                <Input placeholder="e.g. Interview Reminder — Technical Round" />
              </Form.Item>
            </Col>
            <Col xs={24} md={10}>
              <Form.Item name="category" label="Category">
                <Select
                  options={categories
                    .filter(c => c.key !== 'all')
                    .map(c => ({ value: c.key, label: c.label }))}
                />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item
            name="subject"
            label="Subject"
            rules={[{ required: true, message: 'A template needs a subject line.' }]}
          >
            <Input placeholder="e.g. Your interview for {{job_title}}" />
          </Form.Item>

          <Form.Item
            name="placeholders"
            label="Placeholders"
            extra="Tokens this template requires, without braces (e.g. candidate_name). Each one must appear in the subject or body whenever the template is edited later."
          >
            <Select
              mode="tags"
              tokenSeparators={[',']}
              placeholder="candidate_name, job_title"
              options={Object.keys(dummyReplacements).map(k => ({ value: k, label: k }))}
            />
          </Form.Item>

          <Form.Item name="body_html" label="Body" required>
            <div className="em-editor-frame">
              <EmailBodyEditor
                initialHtml=""
                onChange={setCreateBody}
                toolbar={FULL_TOOLBAR}
                height={320}
              />
            </div>
          </Form.Item>

          <Form.Item
            name="is_active"
            label="Active"
            valuePropName="checked"
            extra="Inactive templates are kept but never sent."
          >
            <Switch />
          </Form.Item>
        </Form>
      </Modal>
      </PageShell>
    </DesignScope>
  );
}
