/**
 * emailPreview.js — client-side mirror of the backend's branded email shell
 * (backend/src/services/emailLayout.service.js).
 *
 * Pipeline Tracker templates are stored as BODY FRAGMENTS; the green AAPNA
 * header, card and footer are added by the backend at send time. Previewing the
 * raw fragment would therefore show something the recipient never receives, so
 * the preview surfaces wrap it the same way.
 *
 * Keep the markup here in step with wrapBrandedEmail() on the backend. Where a
 * preview endpoint already returns a `wrapper` payload (the Pipeline Drawer
 * modals), prefer that — it is generated by the send path itself and cannot
 * drift. This module exists for surfaces with no such endpoint, i.e. the Email
 * Template Management "Live Preview" tab.
 */

const LOGO = 'https://www.aapnainfotech.com/wp-content/uploads/2021/09/aapna-gptw-black.png';
const ACCENT = '#4f2fb8';

/**
 * True when the HTML already carries its own document shell — mirrors
 * isFullHtmlDocument() on the backend. Already-branded templates (Welcome,
 * Shortlist, Duplicate Alert, …) must render untouched.
 *
 * @param {string} html
 * @returns {boolean}
 */
export function isFullHtmlDocument(html) {
  if (typeof html !== 'string' || html.trim() === '') return false;
  return /<!DOCTYPE\s|<html[\s>]|<body[\s>]/i.test(html);
}

/**
 * Escapes text for the header band. `title` is the email SUBJECT — free text
 * that may contain & or < — so it is never interpolated raw. Mirrors
 * escapeHtml() in the backend's emailLayout.service.js.
 */
function escapeHtml(text) {
  return String(text ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Wraps a body fragment in the branded shell for preview purposes.
 * Returns full documents unchanged, so it is safe to call on any template.
 *
 * @param {string} bodyHtml
 * @param {{title?: string, subtitle?: string}} [opts] - `title` is the subject line
 * @returns {string}
 */
export function wrapBrandedPreview(bodyHtml, { title = '', subtitle = 'AAPNA Infotech — Recruitment Update' } = {}) {
  if (isFullHtmlDocument(bodyHtml)) return bodyHtml;
  const body = typeof bodyHtml === 'string' ? bodyHtml : '';
  const safeTitle = escapeHtml(title).trim();

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>`
    + `<body style="margin:0;padding:0;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif">`
    + `<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:30px 10px"><tr><td align="center">`
    + `<table width="620" cellpadding="0" cellspacing="0" style="max-width:620px;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 6px 24px rgba(0,0,0,0.08)">`
    + `<tr><td style="background:${ACCENT};padding:32px 40px;text-align:center">`
    + `<img src="${LOGO}" width="190" alt="AAPNA Infotech" style="display:block;margin:0 auto 16px auto">`
    + (safeTitle ? `<h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:800">${safeTitle}</h1>` : '')
    + `<p style="margin:6px 0 0 0;color:#e0dbf4;font-size:13px">${escapeHtml(subtitle)}</p>`
    + `</td></tr>`
    + `<tr><td style="padding:32px 40px 24px 40px;font-size:15px;color:#374151;line-height:1.8">${body}</td></tr>`
    + `<tr><td style="background:#f3f4f6;padding:16px;text-align:center;font-size:12px;color:#9ca3af">`
    + `This email was sent by AAPNA Infotech's recruitment system.<br>`
    + `&copy; 2026 AAPNA Infotech. All rights reserved.`
    + `</td></tr>`
    + `</table></td></tr></table></body></html>`;
}

export default { wrapBrandedPreview, isFullHtmlDocument };
